# [An introduction to Numpy and Scipy](https://sites.engineering.ucsb.edu/~shell/che210d/numpy.pdf)

In [7]:
import numpy as np
a = np.array([1, 4, 5, 8], float)
print(a)
type(a)

[1. 4. 5. 8.]


numpy.ndarray

In [2]:
a[:2]

[1. 4.]


In [8]:
a[3]

8.0

In [9]:
a[0] = 5.
a

array([5., 4., 5., 8.])

In [10]:
m = np.array([[1, 2, 3], [4, 5, 6]], float)
print (m)

[[1. 2. 3.]
 [4. 5. 6.]]


In [13]:
print(m[0,0])
print(m[0,1])

1.0
2.0


In [15]:
m[1,:]

array([4., 5., 6.])

In [16]:
m[:,2]

array([3., 6.])

In [17]:
m[-1,-2]

5.0

In [19]:
m.shape

(2, 3)

In [20]:
m.dtype

dtype('float64')

In [21]:
len(m)

2

In [22]:
len(m[0])

3

In [23]:
2 in m

True

In [24]:
0 in m

False

In [31]:
b = np.array(range(10), float)
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [32]:
b = b.reshape(5,2)
b

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [33]:
b.shape

(5, 2)

In [38]:
c = np.array([1, 2, 3], float)
d = c
e = c.copy()
c[0] = 0

In [39]:
c

array([0., 2., 3.])

In [40]:
d

array([0., 2., 3.])

In [41]:
e

array([1., 2., 3.])

In [42]:
f = np.array([1,2,3], float)
f.tolist()

[1.0, 2.0, 3.0]

In [43]:
list(f)

[1.0, 2.0, 3.0]

In [44]:
g = np.array([1,2,3],float)
s = g.tostring()

In [45]:
s

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [46]:
np.fromstring(s)

array([1., 2., 3.])

In [49]:
h = np.array([1,2,3], float)
h 

array([1., 2., 3.])

In [51]:
h.fill(0)
h

array([0., 0., 0.])

In [52]:
i = np.array(range(6), float).reshape(2,3)
i

array([[0., 1., 2.],
       [3., 4., 5.]])

In [53]:
i.transpose()

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [55]:
j = np.array([[1,2,3],[4,5,6]],float)
j

array([[1., 2., 3.],
       [4., 5., 6.]])

In [56]:
j.flatten()

array([1., 2., 3., 4., 5., 6.])

In [61]:
k = np.array([1,2], float)
l = np.array([3,4,5,6], float)
m = np.array([8,9], float)
np.concatenate((k,l,m))

array([1., 2., 3., 4., 5., 6., 8., 9.])

In [62]:
n = np.array([[1,2],[3,4]],float)
o = np.array([[5,6],[7,8]],float)
np.concatenate((n,o))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [63]:
np.concatenate((n,o), axis=0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [64]:
np.concatenate((n,o), axis=1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [65]:
p = np.array([1,2,3], float)
p

array([1., 2., 3.])

In [66]:
p[:,np.newaxis]

array([[1.],
       [2.],
       [3.]])

In [68]:
p[:,np.newaxis].shape

(3, 1)

In [73]:
q = np.array([1,2,3], float)
q

array([1., 2., 3.])

In [74]:
q[np.newaxis,:]

array([[1., 2., 3.]])

In [75]:
q[np.newaxis,:].shape

(1, 3)