# [An introduction to Numpy and Scipy](https://sites.engineering.ucsb.edu/~shell/che210d/numpy.pdf)
NumPy   and   SciPy   are   open-source   add-on   modules   to   Python   that   providecommon mathematical  and  numerical  routines inpre-compiled,  fast  functions.    These  are  growing  into highly  mature  packages  that  provide  functionality  that  meets,  or  perhaps  exceeds,  that associated  with  common  commercial  software  like  MatLab.The  NumPy  (Numeric  Python) package  provides  basic  routines  for  manipulating  large  arrays  and  matrices  of  numeric  data.  The  SciPy  (Scientific  Python)  package  extends  the  functionality  of  NumPy  with  a  substantial collection of useful algorithms, like minimization, Fourier transformation, regression, and other applied mathematical techniques.

## Arrays
The  central  feature  of  NumPy  is  the arrayobject  class.   Arrays  are  similar  to  lists  in  Python, except  that  every  element  of  an  array  must  be  of  the  same  type,  typically  a  numeric  type  like floator int.  Arrays make operations with large amounts of numeric data very fast and are generally much more efficient than lists.An array can be created from a list:

In [1]:
import numpy as np
a = np.array([1, 4, 5, 8], float)
print(a)
type(a)

[1. 4. 5. 8.]


numpy.ndarray

Here, the function arraytakes two arguments: the list to be converted into the array and the type of each member of the list.Array elements are accessed, sliced, and manipulated just like lists:

In [2]:
a[:2]

array([1., 4.])

In [3]:
a[3]

8.0

In [4]:
a[0] = 5.
a

array([5., 4., 5., 8.])

Arrays  can  be  multidimensional.    Unlike  lists,  different  axes  are  accessed  using  commas insidebracket notation.  Here is an example with a two-dimensional array (e.g., a matrix):

In [5]:
m = np.array([[1, 2, 3], [4, 5, 6]], float)
print (m)

[[1. 2. 3.]
 [4. 5. 6.]]


In [6]:
print(m[0,0])
print(m[0,1])

1.0
2.0


Array  slicing  works  with  multiple  dimensions  in  the  same  way  as  usual,  applying  each  slice specification as a filter to a specified dimension.  Use of a single ":" in a dimension indicates the use of everything along that dimension:

In [7]:
m[1,:]

array([4., 5., 6.])

In [8]:
m[:,2]

array([3., 6.])

In [9]:
m[-1,-2]

5.0

The shape property of an array returns a tuple with the size of each array dimension:

In [10]:
m.shape

(2, 3)

The dtype property tells you what type of values are stored by the array:

In [11]:
m.dtype

dtype('float64')

Here, float64 is  a  numeric  type  that  NumPy  uses  to  store  double-precision  (8-byte)  real numbers, similar to the floattype in Python.When used with an array, the lenfunction returns the length of the first axis:

In [12]:
len(m)

2

In [13]:
len(m[0])

3

The instatement can be used to test if values are present in an array:

In [14]:
2 in m

True

In [15]:
0 in m

False

Arrays can be reshaped using tuples that specify new dimensions.  In the following example, we turn a ten-element one-dimensional array into a two-dimensional one whose first axis has five elements andwhose second axis has two elements

In [16]:
b = np.array(range(10), float)
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
b = b.reshape(5,2)
b

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [18]:
b.shape

(5, 2)

Notice that the reshapefunction creates a new array and does not itself modify the original array.Keep  in  mind  that  Python's  name-binding  approach  still  applies  to  arrays.    
The copy function can be used to create a new, separate copy of an array in memory if needed:

In [19]:
c = np.array([1, 2, 3], float)
d = c
e = c.copy()
c[0] = 0

In [20]:
c

array([0., 2., 3.])

In [21]:
d

array([0., 2., 3.])

In [22]:
e

array([1., 2., 3.])

Lists can also be created from arrays:

In [23]:
f = np.array([1,2,3], float)
f.tolist()

[1.0, 2.0, 3.0]

In [24]:
list(f)

[1.0, 2.0, 3.0]

One  can  convert  the  raw  data  in  an  array  to  a binary  string  (i.e.,  not  in  human-readable form)  using the tostring function.  The fromstring function then allows an array to be created from  this  data  later  on.    These  routines  are  sometimes  convenient  for  saving  large  amount  of array data in files that can be read later on:

In [25]:
g = np.array([1,2,3],float)
s = g.tostring()

In [26]:
s

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [27]:
np.fromstring(s)

array([1., 2., 3.])

One can fill an array with a single value:

In [28]:
h = np.array([1,2,3], float)
h 

array([1., 2., 3.])

In [29]:
h.fill(0)
h

array([0., 0., 0.])

Transposed  versions  of  arrays  can  also  be  generated,  which  will  create  a  new  array  with  the final two axes switched:

In [30]:
i = np.array(range(6), float).reshape(2,3)
i

array([[0., 1., 2.],
       [3., 4., 5.]])

In [31]:
i.transpose()

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

One-dimensional versions of multi-dimensional arrays can be generated with flatten:

In [32]:
j = np.array([[1,2,3],[4,5,6]],float)
j

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
j.flatten()

array([1., 2., 3., 4., 5., 6.])

Two  or  more  arrays  can  be  concatenated  together  using  the concatenate function  with  a tuple of the arrays to be joined:

In [34]:
k = np.array([1,2], float)
l = np.array([3,4,5,6], float)
m = np.array([8,9], float)
np.concatenate((k,l,m))

array([1., 2., 3., 4., 5., 6., 8., 9.])

If an array has more than one dimension, it is possible to specify the axis along which multiple arrays  are  concatenated.    By  default  (without  specifying  the  axis),  NumPy concatenates  along the first dimension:

In [35]:
n = np.array([[1,2],[3,4]],float)
o = np.array([[5,6],[7,8]],float)
np.concatenate((n,o))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [36]:
np.concatenate((n,o), axis=0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [37]:
np.concatenate((n,o), axis=1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

Finally, the dimensionality of an array can be increased using the newaxis constant in bracket notation:

In [38]:
p = np.array([1,2,3], float)
p

array([1., 2., 3.])

In [39]:
p[:,np.newaxis]

array([[1.],
       [2.],
       [3.]])

In [40]:
p[:,np.newaxis].shape

(3, 1)

In [41]:
q = np.array([1,2,3], float)
q

array([1., 2., 3.])

In [42]:
q[np.newaxis,:]

array([[1., 2., 3.]])

In [43]:
q[np.newaxis,:].shape

(1, 3)

Notice here that in each case the new array has two dimensions; the one created by newaxishas  a  length  of  one.    The newaxis approach  is  convenient  for  generating  the  proper-dimensioned arrays for vector and matrix mathematics.